style: 'github'
languages:
  1c: '1C:Enterprise (v7, v8)'
  abnf: 'Augmented Backus-Naur Form'
  accesslog: 'Access log'
  actionscript: 'ActionScript'
  ada: 'Ada'
  angelscript: 'AngelScript'
  apache: 'Apache'
  applescript: 'AppleScript'
  arcade: 'ArcGIS Arcade'
  arduino: 'Arduino'
  armasm: 'ARM Assembly'
  asciidoc: 'AsciiDoc'
  aspectj: 'AspectJ'
  autohotkey: 'AutoHotkey'
  autoit: 'AutoIt'
  avrasm: 'AVR Assembler'
  awk: 'Awk'
  axapta: 'Axapta'
  bash: 'Bash'
  basic: 'Basic'
  bnf: 'Backus–Naur Form'
  brainfuck: 'Brainfuck'
  cal: 'C/AL'
  capnproto: 'Cap’n Proto'
  ceylon: 'Ceylon'
  clean: 'Clean'
  clojure-repl: 'Clojure REPL'
  clojure: 'Clojure'
  cmake: 'CMake'
  coffeescript: 'CoffeeScript'
  coq: 'Coq'
  cos: 'Caché Object Script'
  cpp: 'C++'
  crmsh: 'crmsh'
  crystal: 'Crystal'
  cs: 'C#'
  csp: 'CSP'
  css: 'CSS'
  d: 'D'
  dart: 'Dart'
  delphi: 'Delphi'
  diff: 'Diff'
  django: 'Django'
  dns: 'DNS Zone file'
  dockerfile: 'Dockerfile'
  dos: 'DOS .bat'
  dsconfig: 'dsconfig'
  dts: 'Device Tree'
  dust: 'Dust'
  ebnf: 'Extended Backus-Naur Form'
  elixir: 'Elixir'
  elm: 'Elm'
  erb: 'ERB (Embedded Ruby)'
  erlang-repl: 'Erlang REPL'
  erlang: 'Erlang'
  excel: 'Excel'
  fix: 'FIX'
  flix: 'Flix'
  fortran: 'Fortran'
  fsharp: 'F#'
  gams: 'GAMS'
  gauss: 'GAUSS'
  gcode: 'G-code (ISO 6983)'
  gherkin: 'Gherkin'
  glsl: 'GLSL'
  gml: 'GML'
  go: 'Go'
  golo: 'Golo'
  gradle: 'Gradle'
  groovy: 'Groovy'
  haml: 'Haml'
  handlebars: 'Handlebars'
  haskell: 'Haskell'
  haxe: 'Haxe'
  hsp: 'HSP'
  htmlbars: 'HTMLBars'
  http: 'HTTP'
  hy: 'Hy'
  inform7: 'Inform 7'
  ini: 'Ini, TOML'
  irpf90: 'IRPF90'
  isbl: 'ISBL'
  java: 'Java'
  javascript: 'JavaScript'
  jboss-cli: 'jboss-cli'
  json: 'JSON'
  julia-repl: 'Julia REPL'
  julia: 'Julia'
  kotlin: 'Kotlin'
  lasso: 'Lasso'
  ldif: 'LDIF'
  leaf: 'Leaf'
  less: 'Less'
  lisp: 'Lisp'
  livecodeserver: 'LiveCode'
  livescript: 'LiveScript'
  llvm: 'LLVM IR'
  lsl: 'Linden Scripting Language'
  lua: 'Lua'
  makefile: 'Makefile'
  markdown: 'Markdown'
  mathematica: 'Mathematica'
  matlab: 'Matlab'
  maxima: 'Maxima'
  mel: 'MEL'
  mercury: 'Mercury'
  mipsasm: 'MIPS Assembly'
  mizar: 'Mizar'
  mojolicious: 'Mojolicious'
  monkey: 'Monkey'
  moonscript: 'MoonScript'
  n1ql: 'N1QL'
  nginx: 'Nginx'
  nimrod: 'Nimrod'
  nix: 'Nix'
  nsis: 'NSIS'
  objectivec: 'Objective-C'
  ocaml: 'OCaml'
  openscad: 'OpenSCAD'
  oxygene: 'Oxygene'
  parser3: 'Parser3'
  perl: 'Perl'
  pf: 'pf'
  pgsql: 'PostgreSQL SQL dialect and PL/pgSQL'
  php: 'PHP'
  plaintext: 'plaintext'
  pony: 'Pony'
  powershell: 'PowerShell'
  processing: 'Processing'
  profile: 'Python profile'
  prolog: 'Prolog'
  properties: 'Properties'
  protobuf: 'Protocol Buffers'
  puppet: 'Puppet'
  purebasic: 'PureBASIC'
  python: 'Python'
  q: 'Q'
  qml: 'QML'
  r: 'R'
  reasonml: 'ReasonML'
  rib: 'RenderMan RIB'
  roboconf: 'Roboconf'
  routeros: 'Microtik RouterOS script'
  rsl: 'RenderMan RSL'
  ruby: 'Ruby'
  ruleslanguage: 'Oracle Rules Language'
  rust: 'Rust'
  sas: 'SAS'
  scala: 'Scala'
  scheme: 'Scheme'
  scilab: 'Scilab'
  scss: 'SCSS'
  shell: 'Shell Session'
  smali: 'Smali'
  smalltalk: 'Smalltalk'
  sml: 'SML'
  sqf: 'SQF'
  sql: 'SQL'
  stan: 'Stan'
  stata: 'Stata'
  step21: 'STEP Part 21'
  stylus: 'Stylus'
  subunit: 'SubUnit'
  swift: 'Swift'
  taggerscript: 'Tagger Script'
  tap: 'Test Anything Protocol'
  tcl: 'Tcl'
  tex: 'TeX'
  thrift: 'Thrift'
  tp: 'TP'
  twig: 'Twig'
  typescript: 'TypeScript'
  vala: 'Vala'
  vbnet: 'VB.NET'
  vbscript-html: 'VBScript in HTML'
  vbscript: 'VBScript'
  verilog: 'Verilog'
  vhdl: 'VHDL'
  vim: 'Vim Script'
  x86asm: 'Intel x86 Assembly'
  xl: 'XL'
  xml: 'HTML, XML'
  xquery: 'XQuery'
  yaml: 'YAML'
  zephir: 'Zephir'